config/routes.rb
NetflixManager::Application.routes.draw do

  devise_for :users

  root :to => "profiles#index"

  match 'netflix_auth/login' => 'netflix_auth#login'
  match 'netflix_auth/link_account' => 'netflix_auth#link_account'
  match 'netflix_auth/link_account_callback' => 'netflix_auth#link_account_callback'

  match 'movie_queues/move' => 'movie_queues#move'
  resources :movie_queues

  match 'profiles' => 'profiles#index'
  match 'profiles/setup' => 'profiles#setup'
  match 'profiles/add' => 'profiles#add'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  belongs_to :user
  
  default_scope :order => 'position'
  
  def disc_queue
    @disc_queue ||= netflix_user.available_disc_queue
  end
  
  #should override the database attribute
  def name
    "#{netflix_user.first_name} #{netflix_user.last_name}"
  end
  
  private
  def netflix_user
    @netflix_user ||= netflix_client.user(netflix_user_id)
  end
  
  def netflix_client
    @netflix_client ||= Netflix::Client.new(user.access_token, user.access_secret)
  end
  
  def reload
    #kill and lazy load later
    @disc_queue = nil
    @netflix_user = nil
    super
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :profiles
  
  def disc_queues
    @disc_queues ||= profiles.map(&:disc_queue)
  end
  
  private
  def netflix_user
    @disc_queues ||= netflix_client.user(self.netflix_user_id)
  end
  
  def netflix_client
    @netflix_client ||= Netflix::Client.new(self.access_token, self.access_secret)
  end
  
  def reload
    #kill and lazy load later
    @disc_queues = nil
    @netflix_user = nil
    super
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  def netflix_auth
    if !current_user.access_token
      redirect_to '/netflix_auth/link_account'
    end
  end
  
  def netflix_client_for_user
    raise 'no current_user found' unless current_user
    @netflix_client_for_user ||= Netflix::Client.new(current_user.access_token, current_user.access_secret)
  end
  
  def netflix_client
    @netflix_client ||= Netflix::Client.new
  end
  
end

app/controllers/movie_queues_controller.rb
class MovieQueuesController < ApplicationController
  before_filter :authenticate_user!  
  
  respond_to :json
  
  def move
    item = params["item"]
    from_queue_id = params["from"]
    from_etag = params["from_etag"]
    to_queue_id = params["to"]
    to_etag = params["to_etag"]
    position = params["position"]
    if item.blank? || from_queue_id.blank? || from_etag.blank? || to_queue_id.blank? || to_etag.blank? || position.blank?
      logger.error "[#{self.class.name}#move] one or more parameters were missing"
      return render :status => 500, :text => "{'exception': 'one or more parameters missing', 'params': #{params.to_json}}"
    end
    logger.debug "[#{self.class.name}#move]: item #{item}, from #{from_queue_id}, to #{to_queue_id}, from_etag #{from_etag}, to_etag #{to_etag}, position #{position}"
    
    from_queue = netflix_client_for_user.user(extract_user_id(from_queue_id)).available_disc_queue
    to_queue = netflix_client_for_user.user(extract_user_id(to_queue_id)).available_disc_queue
    
    item_title_ref = extract_title_ref(item)
    begin
      to_queue.add(item_title_ref, (position.to_i + 1))
      item =~ /.*\/(\d+)\/\d+$/
      item_position = $1
      #from_queue.remove(item)
      from_queue.remove(item_position)
      @profiles = current_user.profiles
      render :json => @profiles.to_json(:only => [:id, :name], :methods => :disc_queue)
    rescue
      logger.error "[#{self.class.name}#move] rescued: #{$!.inspect}"
      render :status => 500, :text => "{'exception': '#{$!.message}'}"
    end
  end
  
  
  private
  def extract_user_id(queue_id)
    queue_id =~ /users\/(.*?)\//
    $1
  end
  
  def extract_title_ref(item_id)
    item_id =~ /queues\/disc\/available\/\d+\/(\d+)/
    $1
  end

end

app/controllers/netflix_auth_controller.rb
require 'oauth/consumer'
require 'oauth/token'

class NetflixAuthController < ApplicationController
  before_filter :authenticate_user!
  
  def link_account_callback
    begin
      oauth_verifier = params[:oauth_verifier]
      request_token = session[:request_token]
      logger.debug "[#{self.class.name}#link_account_callback] request_token #{request_token.inspect}"
      access_token = netflix_client.handle_oauth_callback(request_token, oauth_verifier)
      logger.debug "[#{self.class.name}#link_account_callback] access_token #{access_token.inspect}"
      #normally, we want to set the netflix_user_id, 
      #but if we already have an access_token for this user, and the user_id is different,
      #we are adding a sub-profile
      if !current_user.access_token && current_user.profiles.count == 0
        current_user.profiles.build(:netflix_user_id => access_token.params["user_id"], :primary => true)
        current_user.access_token = access_token.token
        current_user.access_secret = access_token.secret
      else
        current_user.profiles.build(:netflix_user_id => access_token.params["user_id"], :primary => false)
      end
      current_user.save
    rescue
      logger.error "[#{self.class.name}#link_account_callback] #{$!.inspect}"
      flash[:alert] = "Error linking account"
    end
    redirect_to :profiles
  end
  
  def link_account 
    oauth_callback_url = netflix_auth_link_account_callback_url
    request_token, auth_url = netflix_client.oauth_via_callback(oauth_callback_url)
    session[:request_token] = request_token
    redirect_to auth_url
  end
  
end

app/controllers/profiles_controller.rb
require 'oauth/consumer'
require 'oauth/token'

class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :netflix_auth
  
  respond_to :json, :html
  
  def index
    @profiles = current_user.profiles
    respond_to do |format|
      format.html 
      format.json { render :json => @profiles.to_json(:only => [:id, :name], :methods => :disc_queue) }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/helpers/movie_queues_helper.rb
module MovieQueuesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def user_id(url)
    user_id = nil
    if user_url =~ /https?:\/\/api.netflix.com\/users\/([^\/]*)\/.*/
      url_segment = $1
      user_id = URI.escape(url_segment)
    end
    user_id
  end
  
  def queue_id(queue_url)
    queue_id = nil
    if queue_url =~ /https?:\/\/api.netflix.com\/users\/((?:[^\/]*)\/queues\/disc\/available).*/
      url_segment = $1
      queue_id = URI.escape(url_segment)
    end
    queue_id
  end
  
  def title_id(item_url)
    item_id = nil
    if item_url =~ /https?:\/\/api.netflix.com\/users\/(?:[^\/]*)\/queues\/disc\/available\/\d+\/(\d+).*/
      item_id = $1
    end
    item_id
  end
end

app/helpers/queue_helper.rb
module QueueHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NetflixManager</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <!-- %= #stylesheet_link_tag "foundation" % -->
  <!-- %= #javascript_include_tag "foundation" % -->
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" id="header">
  <div class="row">
    <div class="six columns">
      <h1>NetflixManager <%= "- #{@title}" if @title %></h1>
    </div>
    <div class="six columns">
      <div id="user_nav" class="right">
        <% if user_signed_in? %>
          <%= current_user.email %>
          <%= link_to "Sign Out", destroy_user_session_path, {:method => 'delete'} %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %>&nbsp;/&nbsp;<%= link_to "Sign In", new_user_session_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container" id="main">
  <div class="row" >
    <div class="four columns">
      <% if notice %>
      <div class="alert-box success">
        <%= notice %>
        <a href="" class="close">&times;</a>
      </div>
      <% end %>
      <% if alert %>
      <div class="alert-box error">
        <%= alert %>
        <a href="" class="close">&times;</a>
      </div>
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>

<div class="container" id="footer">
  <div class="row">
    <div class="4 columns">
      This site created by <a href="mailto:deanholdren[at]gmail.com">Dean Holdren</a>
    </div>
  </div>
</div>
</body>
</html>

app/views/profiles/index.html.erb
<div id="profiles" class="row" >
<% @profiles.each do |profile|
	 queue = profile.disc_queue %>
<!--% @queues.each do |queue| % -->
  <%= div_for profile, {:class=>"three columns"} do %>
    <h2><%= profile.name %></h2>
    <ul class="queue queueConnect" id="queue_<%= queue.id %>" etag="<%=queue.etag%>">
    <% queue.discs.each do |disc| %>
      <li class="ui-state-default queue_item" id="queue_item_<%= disc.id %>">
        <%= disc.title %>
      </li>
    <% end %>
    </ul>
  <% end %>
<% end %>
<% unless @profiles.length >= 4 %>
  <div class="three columns">
    <%= button_to "Add profile", netflix_auth_link_account_path, {:class => "nice small radius blue button"} %>
  </div>
<% end %>
</div>

app/views/profiles/setup.html.erb
<div>
This is where you link your sub profiles
<br/><br/>
We only know of your main profile, click the button below, and then be sure to log in to your other profile
<br/><br/>
<!--iframe width=800 src="http://netflix.com" ></iframe -->
<%= button_to "Add sub-profile", netflix_auth_link_account_path %>

</div>